### GET all readings (just here fortemporary testing purposes) ---> delete afterwards
GET http://localhost:8080/rest/readings/all

### GET all readings for a certain customer
GET http://localhost:8080/rest/readings/?customer=8670e527-3f5e-44cc-ae61-fba80268bd7f

### GET all readings for a certain customer in a certain time period
GET http://localhost:8080/rest/readings/?customer=8670e527-3f5e-44cc-ae61-fba80268bd7f&start=2010-07-07&end=2024-05-20&kindOfMeter=HEATING

### GET reading by id
GET http://localhost:8080/rest/readings/ff2f148b-c7b2-49e0-984c-d2c5e30ba199

### DELETE reading by id
DELETE http://localhost:8080/rest/readings/ff2f148b-c7b2-49e0-984c-d2c5e30ba199

### POST reading
POST http://localhost:8080/rest/readings
Content-Type: application/json
Accept: application/json

{
  "customer": {
    "firstName": "Vera",
    "lastName": "Veeera",
    "gender": "W"
  },
  "dateOfReading": "2021-09-12",
  "meterId": "Xr-2021-2312434xz",
  "substitute": false,
  "meterCount": 8.111,
  "kindOfMeter": "HEATING"
}


### PUT reading
PUT http://localhost:8080/rest/readings
Content-Type: application/json
Accept: text/plain

{
  "customer": {
    "firstName": "VeraVeraVera",
    "lastName": "Veeera",
    "gender": "W"
  },
  "dateOfReading": "2021-09-12",
  "id": "3c650ebb-4be7-40d8-af3d-e42cdafd7aa0",
  "meterId": "Xr-2021-2312434xz",
  "substitute": false,
  "meterCount": 8.111,
  "kindOfMeter": "HEATING"
}


//riprendi da qui: put not mapping the id properly, maybe because of two nested objects?
//riprendi da qui: put not mapping the id properly, maybe because of two nested objects?
//riprendi da qui: put not mapping the id properly, maybe because of two nested objects?
//riprendi da qui: put not mapping the id properly, maybe because of two nested objects?
//riprendi da qui: put not mapping the id properly, maybe because of two nested objects?
//riprendi da qui: put not mapping the id properly, maybe because of two nested objects?
//set up tests kinda so la la
### PUT reading step by step
PUT http://localhost:8080/rest/readings
Content-Type: application/json
Accept: text/plain

{
  "id": "3c650ebb-4be7-40d8-af3d-e42cdafd7aa0",
  "dateOfReading": "2021-09-12",
  "meterId": "Xr-2021-2312434xz",
  "substitute": false,
  "meterCount": 8.111,
  "kindOfMeter": "HEATING",
  "customer": {
    "firstName": "VeraVeraVera",
    "lastName": "Veeera",
    "gender": "W"
  }
}


